[package]
name = "tiny-dfr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cairo-rs = { version = "0.17", default-features = false }
drm = "0.9"
anyhow = "1"
input = "0.8"
libc = "0.2"
input-linux = "0.6"
input-linux-sys = "0.8"
nix = "0.26"
